//
//  Copyright (C) 1999 by
//  id Software, Chi Hoang, Lee Killough, Jim Flynn, Rand Phares, Ty Halderman
//
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
// DESCRIPTION:
//  all external data is defined here
//  most of the data is loaded into different structures at run time
//  some internal structures shared by many modules are here
//
//-----------------------------------------------------------------------------

#ifndef __DOOMDATA__
#define __DOOMDATA__

#include "m_fixed.h"

typedef enum {
  MFMT_Invalid,
  MFMT_Doom,
  MFMT_UDMF,
} mapformat_t;

extern mapformat_t mapformat;

//
// Map level types.
// The following data structures define the persistent format
// used in the lumps of the WAD files.
//

// Lump order in a map WAD: each map needs a couple of lumps
// to provide a complete scene geometry description.
enum {
  ML_LABEL,             // A separator, name, ExMx or MAPxx
  ML_THINGS,            // Monsters, items..
  ML_LINEDEFS,          // LineDefs, from editing
  ML_SIDEDEFS,          // SideDefs, from editing
  ML_VERTEXES,          // Vertices, edited and BSP splits generated
  ML_SEGS,              // LineSegs, from LineDefs split by BSP
  ML_SSECTORS,          // SubSectors, list of LineSegs
  ML_NODES,             // BSP nodes
  ML_SECTORS,           // Sectors, from editing
  ML_REJECT,            // LUT, sector-sector visibility
  ML_BLOCKMAP,          // LUT, motion clipping, walls/grid element
  ML_BEHAVIOR,          // Hexen-format, ACS byte code. Unsupported
};

// A single Vertex.
typedef struct {
  short x,y;
} mapvertex_t;

// A SideDef, defining the visual appearance of a wall,
// by setting textures and offsets.
typedef struct {
  short textureoffset;
  short rowoffset;
  char  toptexture[8];
  char  bottomtexture[8];
  char  midtexture[8];
  short sector;  // Front sector, towards viewer.
} mapsidedef_t;

// A LineDef, as used for editing, and as input to the BSP builder.

typedef struct {
  // [FG] extended nodes
  unsigned short v1;
  unsigned short v2;
  unsigned short flags;
  short special;
  short tag;
  unsigned short sidenum[2];  // sidenum[1] will be -1 (NO_INDEX) if one sided
} maplinedef_t;

//
// LineDef attributes.
//

// Solid, is an obstacle.
#define ML_BLOCKING             1

// Blocks monsters only.
#define ML_BLOCKMONSTERS        2

// Backside will not be drawn if not two sided.
#define ML_TWOSIDED             4

// If a texture is pegged, the texture will have
// the end exposed to air held constant at the
// top or bottom of the texture (stairs or pulled
// down things) and will move with a height change
// of one of the neighbor sectors.
// Unpegged textures always have the first row of
// the texture at the top pixel of the line for both
// top and bottom textures (use next to windows).

// upper texture unpegged
#define ML_DONTPEGTOP           8

// lower texture unpegged
#define ML_DONTPEGBOTTOM        16

// In AutoMap: don't map as two sided: IT'S A SECRET!
#define ML_SECRET               32

// Sound rendering: don't let sound cross two of these.
#define ML_SOUNDBLOCK           64

// Don't draw on the automap at all.
#define ML_DONTDRAW             128

// Set if already seen, thus drawn in automap.
#define ML_MAPPED               256

//jff 3/21/98 Set if line absorbs use by player
//allow multiple push/switch triggers to be used on one push
#define ML_PASSUSE      512

// Reserved by EE
// SoM 9/02/02: 3D Middletexture flag!
#define ML_3DMIDTEX             1024

// haleyjd 05/02/06: Although it was believed until now that a reserved line
// flag was unnecessary, a problem with Ultimate DOOM E2M7 has disproven this
// theory. It has roughly 1000 linedefs with 0xFE00 masked into the flags, so
// making the next line flag reserved and using it to toggle off ALL extended
// flags will preserve compatibility for such maps. I have been told this map
// is one of the first ever created, so it may have something to do with that.
#define ML_RESERVED             2048

// mbf21
#define ML_BLOCKLANDMONSTERS    4096
#define ML_BLOCKPLAYERS         8192

// Sector definition, from editing.
typedef struct {
  short floorheight;
  short ceilingheight;
  char  floorpic[8];
  char  ceilingpic[8];
  short lightlevel;
  short special;
  short tag;
} mapsector_t;

// SubSector, as generated by BSP.
typedef struct {
  // [FG] extended nodes
  unsigned short numsegs;
  unsigned short firstseg;    // Index of first one; segs are stored sequentially.
} mapsubsector_t;

// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
typedef struct {
  // [FG] extended nodes
  unsigned short v1;
  unsigned short v2;
  short angle;
  unsigned short linedef;
  short side;
  short offset;
} mapseg_t;

// BSP node structure.

// Indicate a leaf.
#define NF_SUBSECTOR_VANILLA 0x8000
#define NF_SUBSECTOR    0x80000000
 // [FG] extended nodes
#define NO_INDEX        ((unsigned short)-1)

typedef struct {
  short x;  // Partition line from (x,y) to x+dx,y+dy)
  short y;
  short dx;
  short dy;
  // Bounding box for each child, clip against view frustum.
  short bbox[2][4];
  // If NF_SUBSECTOR its a subsector, else it's a node of another subtree.
  unsigned short children[2];
} mapnode_t;

// Thing definition, position, orientation and type,
// plus skill/visibility flags and attributes.
typedef struct {
  short x;
  short y;
  short angle;
  short type;
  short options;
} mapthing_t;

//
//
// [EA] Universal Doom Map Format (UDMF) support
//
//

typedef enum {
  UDMF_Lump_LABEL,
  UDMF_Lump_TEXTMAP,
  UDMF_Lump_BLOCKMAP,
  UDMF_Lump_REJECT,
  UDMF_Lump_ZNODES,
  UDMF_Lump_ENDMAP,
  UDMF_Lump_MAX,
} UDMF_Lumps_t;

typedef enum {
  UDMF_Namespace_Invalid = -1,
  UDMF_Namespace_Doom,
  UDMF_Namespace_Doom_Vanilla,
  UDMF_Namespace_Doom_Boom,
  UDMF_Namespace_Doom_MBF,
  UDMF_Namespace_Doom_MBF21,
  UDMF_Namespace_Doom_ID24,
  UDMF_Namespace_MAX,
} UDMF_Namespace_t;

const char * const UDMF_Lumps[] = {
  [UDMF_Lump_LABEL]    = "-",
  [UDMF_Lump_TEXTMAP]  = "TEXTMAP",
  [UDMF_Lump_BLOCKMAP] = "BLOCKMAP",
  [UDMF_Lump_REJECT]   = "REJECT",
  [UDMF_Lump_ZNODES]   = "ZNODES",
  [UDMF_Lump_ENDMAP]   = "ENDMAP",
  [UDMF_Lump_MAX]      = NULL,
};

const char * const UDMF_Namespaces[] = {
  [UDMF_Namespace_Doom]         = "Doom",
  [UDMF_Namespace_Doom_Vanilla] = "Doom_Vanilla",
  [UDMF_Namespace_Doom_Boom]    = "Doom_Boom",
  [UDMF_Namespace_Doom_MBF]     = "Doom_MBF",
  [UDMF_Namespace_Doom_MBF21]   = "Doom_MBF21",
  [UDMF_Namespace_Doom_ID24]    = "Doom_ID24",
  [UDMF_Namespace_MAX]          = NULL,
};

typedef enum {
  UDMF_ThingSkill1       = 0x00000001,
  UDMF_ThingSkill2       = 0x00000002,
  UDMF_ThingSkill3       = 0x00000004,
  UDMF_ThingSkill4       = 0x00000008,
  UDMF_ThingSkill5       = 0x00000010,
  UDMF_ThingAmbush       = 0x00000020,
  UDMF_ThingSingleplayer = 0x00000040,
  UDMF_ThingDeathmatch   = 0x00000080,
  UDMF_ThingCooperative  = 0x00000100,
  UDMF_ThingFriendly     = 0x00000200, // MBF
} UDMF_ThingFlags_t;

typedef enum {
  UDMF_LineBlocking          = 0x00000001,
  UDMF_LineBlockMonsters     = 0x00000002,
  UDMF_LineTwosided          = 0x00000004,
  UDMF_LineDontPegTop        = 0x00000008,
  UDMF_LineDontPegNottom     = 0x00000010,
  UDMF_LineSecret            = 0x00000020,
  UDMF_LineBlockSound        = 0x00000040,
  UDMF_LineDontDraw          = 0x00000080,
  UDMF_LineMapped            = 0x00000100,
  UDMF_LinePassuse           = 0x00000200, // Boom
  UDMF_LineBlockLandMonsters = 0x00000400, // MBF21
  UDMF_LineBlockPlayers      = 0x00000800, // MBF21
} UDMF_LinedefFlags_t;

typedef struct {
  int     id;
  int     type; // DoomEdNum
  fixed_t x;
  fixed_t y;
  fixed_t height; // Floor by default -- ceiling when SPAWNCEILING is set
  short   angle;
  int     flags;
} UDMF_Thing_t;

typedef struct {
  fixed_t x;
  fixed_t y;
} UDMF_Vertex_t;

typedef struct {
  int id;
  int v1;
  int v2;
  int special;
  int sidefront;
  int sideback;
  int flags;
} UDMF_Linedef_t;

typedef struct {
  int         offsetx;
  int         offsety;
  const char *texturetop;
  const char *texturemiddle;
  const char *texturebottom;
  int         sector;
} UDMF_Sidedef_t;

typedef struct {
  int         id;
  int         heightfloor;
  int         heightceiling;
  const char *texturefloor;
  const char *textureceiling;
  int         lightlevel;
  int         special;
} UDMF_Sector_t;

#endif // __DOOMDATA__

//----------------------------------------------------------------------------
//
// $Log: doomdata.h,v $
// Revision 1.4  1998/05/03  22:39:10  killough
// beautification
//
// Revision 1.3  1998/03/23  06:42:57  jim
// linedefs reference initial version
//
// Revision 1.2  1998/01/26  19:26:37  phares
// First rev with no ^Ms
//
// Revision 1.1.1.1  1998/01/19  14:02:51  rand
// Lee's Jan 19 sources
//
//----------------------------------------------------------------------------
